[[main]]
name = "About"
url = "/#about"
weight = 20

[[main]]
name = "Skills"
url = "/#skills"
weight = 30

[[main]]
name = "Experience"
url = "/#experience"
weight = 40

[[main]]
name = "Tech Stack"
url = "/#technical"
weight = 50

[[main]]
name = "Contact"
url = "/#contact"
weight = 60
#
#[[main]]
#name = "Blog"
#url = "/blog/"
#weight = 60
#
#[[main]]
#name = "Engineering"
#url = "/engineering/"
#weight = 50
#pre = "engineering"
#
#[[main]]
#name = "Contributions"
#url = "/contributions/"
#weight = 51
#pre = "contributions"
#
